### ISSUE TITLE
add support for retrieving document thumbnail image

### ISSUE THREAD

**Issue by petri** [glenfant/openxmllib#15]
I am happy to implement this, but I am not sure what's the proper way to retrieve the thumbnail.

I created a PPT and DOC and in both, there is a top-level `_rels` folder that has a `.rels` file inside, in which there is a reference to the `thumbnail.jpg`file.

@glenfant, would you be ok with that as a means to look up the document thumbnail?

I am planning to add support for getting at the thumbnail from Products.OpenXML as well - I'll add issue there once this part is done.

**Comment by petri** [comment]
Ah, looks like the `_rels/.rels` file is indeed standard, so what I proposed should be ok? (https://en.wikipedia.org/wiki/Office_Open_XML_file_formats)

**Comment by glenfant** [comment]
Hi,

Thanks @petri for supporting the ooooold openxmllib. Feel free to fork, work and send a PR for this valuable feature.

IMO, due to its nature, the thumbnail should be provided by a dedicated method, and not as part of the document metadata.

**Comment by petri** [comment]
Implemented in PR #17.

**Comment by petri** [comment]
@glenfant can you give me commit rights to this repository and Products.OpenXml, please, together with PyPI release rights? 

I've already pushed first working version of https://github.com/koodaamo/collective.documentfile that needs updated Products.OpenXml & openxmllib versions.

**Comment by glenfant** [comment]
@petri : hello and sorry to be so late, I didn't find time for all required stuff.

I just grant you  push / tag / accept PR permissions to this repository.

You could do the same on Products.OpenXML since you are member of the "collective" group.

Please provide me your PyPI username to let you release the future bundles of these two packages.

**Comment by petri** [comment]
Ok thanks! My PyPI username is simply 'petri'.

**Comment by glenfant** [comment]
@petri Sorry, I'm @ the office and I don't remember my PyPI password. I'll do this this evening from home.

**Comment by petri** [comment]
@glenfant ok thanks, waiting for that...

**Comment by petri** [comment]
@glenfant any change you'd find time to grant me those PyPI rights for this pkg & Products.OpenXml? Thanks.
